# Demo config file for OMC cron tasks

[[task]]
name = "Im alive"
interval = {second = 3}
command = "echo"
params = ["i'am alive"]

[[task]]
name = "list folder"
interval = {second = 10}
command = "ls"
params = ['-a', '-l']
